In [1]:
import pandas as pd

In [2]:
caminho_importacao = 'C:/Users/hiury/OneDrive/Área de Trabalho/IFCE/projeto_indicium/datasets/raw/custos_importacao.json'
df_importacao = pd.read_json(caminho_importacao)

In [15]:
df_importacao.head()

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 10583.63}, {'start_date': '15/06/2018', 'usd_price': 8778.36}, {'start_date': '25/09/2018', 'usd_price': 8023.87}, {'start_date': '19/03/2019', 'usd_price': 8772.78}, {'start_date': '17/01/2020', 'usd_price': 7918.18}, {'start_date': '17/06/2020', 'usd_price': 6310.01}, {'start_date': '02/07/2021', 'usd_price': 6586.7}, {'start_date': '16/05/2022', 'usd_price': 6538.2}, {'start_date': '28/02/2023', 'usd_price': 6360.91}, {'start_date': '17/10/2023', 'usd_price': 6574.8}, {'start_date': '16/02/2024', 'usd_price': 6657.12}, {'start_date': '22/02/2024', 'usd_price': 6703.2}, {'start_date': '15/03/2024', 'usd_price': 6633.66}, {'start_date': '02/08/2024', 'usd_price': 5774.5}, {'start_date': '08/04/2025', 'usd_price': 5579.75}]"
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 4325.09}, {'start_date': '06/07/2022', 'usd_price': 2577.22}, {'start_date': '24/05/2023', 'usd_price': 2829.74}, {'start_date': '05/11/2025', 'usd_price': 2602.27}]"
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 2549.21}, {'start_date': '26/07/2018', 'usd_price': 2423.45}, {'start_date': '27/06/2019', 'usd_price': 2335.69}, {'start_date': '17/07/2019', 'usd_price': 2399.28}, {'start_date': '14/10/2019', 'usd_price': 2187.31}, {'start_date': '04/12/2020', 'usd_price': 1745.49}, {'start_date': '21/06/2022', 'usd_price': 1753.77}]"
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909.55}, {'start_date': '22/11/2016', 'usd_price': 1010.42}, {'start_date': '19/04/2017', 'usd_price': 1080.89}, {'start_date': '22/11/2018', 'usd_price': 887.7}, {'start_date': '21/09/2022', 'usd_price': 654.31}, {'start_date': '28/11/2023', 'usd_price': 692.14}, {'start_date': '13/03/2024', 'usd_price': 679.13}, {'start_date': '10/03/2025', 'usd_price': 583.85}]"
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 6006.45}, {'start_date': '17/01/2017', 'usd_price': 7374.9}, {'start_date': '18/02/2021', 'usd_price': 4364.4}, {'start_date': '03/05/2022', 'usd_price': 4718.61}, {'start_date': '24/05/2022', 'usd_price': 4920.79}, {'start_date': '15/08/2023', 'usd_price': 4752.24}, {'start_date': '24/09/2024', 'usd_price': 4327.37}, {'start_date': '24/07/2025', 'usd_price': 4285.3}]"

In [4]:
df_importacao_explodido = df_importacao.explode('historic_data')
pd.set_option('display.max_colwidth', None)
df_importacao_explodido

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '10/08/2016', 'usd_price': 10583.63}"
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '15/06/2018', 'usd_price': 8778.36}"
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '25/09/2018', 'usd_price': 8023.87}"
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '19/03/2019', 'usd_price': 8772.78}"
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '17/01/2020', 'usd_price': 7918.18}"
...,...,...,...,...
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '01/06/2023', 'usd_price': 326.88}"
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '31/01/2024', 'usd_price': 332.26}"
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '29/08/2024', 'usd_price': 292.03}"
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '04/10/2024', 'usd_price': 300.96}"
149,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '25/10/2024', 'usd_price': 288.9}"

In [9]:
df_historico = pd.json_normalize(df_importacao_explodido['historic_data'])
df_importacao_explodido = df_importacao_explodido.reset_index(drop=True)
df_importacao_final = pd.concat([
    df_importacao_explodido[['product_id', 'product_name', 'category']],
    df_historico
], axis=1)

df_importacao_final

,product_id,product_name,category,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,10/08/2016,10583.63
1,1,Transponder AIS Maré Magnum,eletrônicos,15/06/2018,8778.36
2,1,Transponder AIS Maré Magnum,eletrônicos,25/09/2018,8023.87
3,1,Transponder AIS Maré Magnum,eletrônicos,19/03/2019,8772.78
4,1,Transponder AIS Maré Magnum,eletrônicos,17/01/2020,7918.18
...,...,...,...,...,...
1255,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,01/06/2023,326.88
1256,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,31/01/2024,332.26
1257,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,29/08/2024,292.03
1258,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,04/10/2024,300.96
1259,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,25/10/2024,288.90

In [19]:
try:
    df_importacao_final.to_csv('C:/Users/hiury/OneDrive/Área de Trabalho/IFCE/projeto_indicium/datasets/processed/df_importacao_final.csv', index=False)
    print(f'Arquivo criado com sucesso!')
except Exception as e:
    print(f'Erro! {e}')

print(f'Antes da normalização: {df_importacao.shape} | Depois: {df_importacao_final.shape}')

Arquivo criado com sucesso!
Antes da normalização: (150, 4) | Depois: (1260, 5)